BUILD_TYPE=Release 
NAME_SUFFIX="" 
OCTAVE_VERSION=4.4.1 
OCTAVE_API_VERSION=6

IPOPT_DEFAULT_LINEAR_SOLVER=ma57
OCTAVEPATH=/home/travis/build/octave-install
KEEP_GOING=1

EXTRA_SWIG_FLAGS="-nodelete"

wget https://ftp.gnu.org/gnu/octave/windows/octave-${OCTAVE_VERSION}-w64.zip
unzip octave-${OCTAVE_VERSION}-w64.zip
cp -R octave-${OCTAVE_VERSION}-w64 octave-64

toolchain.cmake:
SET(CMAKE_SYSTEM_NAME Windows)
SET(CMAKE_SYSTEM_VERSION 1)
SET(PREFIX x86_64-w64-mingw32)

SET(CMAKE_C_COMPILER   x86_64-w64-mingw32-gcc)
SET(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++)
SET(CMAKE_Fortran_COMPILER x86_64-w64-mingw32-gfortran)
set(CMAKE_RC_COMPILER x86_64-w64-mingw32-windres)

SET(CMAKE_FIND_ROOT_PATH $MINGW_ROOT/x86_64-w64-mingw32)
SET(CMAKE_CXX_FLAGS "$CPPFLAGS -fno-ipa-cp-clone" CACHE STRING "" FORCE)
SET(CMAKE_C_FLAGS "-fno-ipa-cp-clone" CACHE STRING "" FORCE)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE NEVER)
set(CMAKE_SHARED_LIBRARY_SUFFIX "dll")

cmake -DFORTRAN_REQUIRED=ON -DWITH_COMMON=ON $casadi_build_flags \
-DOCTAVE_INCLUDE_DIRS=$HOME/build/octave-${OCTAVE_VERSION}/include/octave-${OCTAVE_VERSION}/octave/ \
-DOCTAVE_LIBRARIES=\"$HOME/build/octave-${OCTAVE_VERSION}/bin/liboctinterp-${OCTAVE_API_VERSION}.dll;$HOME/build/octave-${OCTAVE_VERSION}/bin/liboctave-${OCTAVE_API_VERSION}.dll\" \
-DWITH_OCTAVE_IMPORT=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWITH_SELFCONTAINED=ON -DBLA_STATIC=ON \
-DBLA_VENDOR=Generic -DBLA_DIR=/home/travis/build/lapack -DWITH_OCTAVE=ON -DWITH_OCTAVE_IMPORT=ON \
-DENABLE_STATIC=OFF -DENABLE_SHARED=ON -DWITH_DEEPBIND=ON -DCMAKE_TOOLCHAIN_FILE=toolchain.cmake \
-DCMAKE_INSTALL_PREFIX=../octave_install -DWITH_EXAMPLES=OFF ..

make install -j2 VERBOSE=1
cp $MINGW_ROOT/lib/gcc/x86_64-w64-mingw32/*win32/*.dll ../octave_install
cp -RL $MINGW_ROOT/x86_64-w64-mingw32/include ../octave_install/casadi/casadi/jit/mingw

RESULT="$HOME/casadi-windows-octave-${OCTAVE_VERSION}-w64.zip"
